version: "3.9"

services:
  web:
    build: .
    command: python myAPI/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myAPI
      - .db_data/db.sqlite3:/db.sqlite3
    ports:
      - "8000:8000"
